acme_test:
    resource: "@AcmeTestBundle/Resources/config/routing.yml"
    prefix:   /

dna_test:
    resource: "@DnaTestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
