_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_main:
    resource: routing.yml

# AcmeDemoBundle routes (to be removed)
_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

lucky_number:
    path:       /lucky/number/{count}
    defaults:   { _controller: AppBundle:Lucky:number, count: 1 }

api_lucky_number:
    path:       /api/lucky/number
    defaults:   { _controller: AppBundle:Lucky:apiNumber }

hello:
    path:       /hello/{firstName}/{lastName}
    defaults:   { _controller: AppBundle:Hello:index, firstName: "No", lastName: "Name" }

hello_redirect:
    path:       /hello_redirect
    defaults:   { _controller: AppBundle:Hello:redirect }

hello_redirect_external:
    path:       /hello_redirect_external
    defaults:   { _controller: AppBundle:Hello:redirectExternal }

hello_error:
    path:       /hello_error/{responseCode}
    defaults:   { _controller: AppBundle:Hello:exampleError, responseCode: 500 }

blog:
    path:           /blog/{page}
    defaults:       { _controller: AppBundle:Blog:index, page: 1 }
    requirements:
        page:   \d+


blog_show:
    path:       /blog/{slug}
    defaults:   { _controller: AppBundle:Blog:show }

product_create:
    path:       /product/create
    defaults:   { _controller: AppBundle:Default:create }

product_show:
    path:       /product/show/{id}
    defaults:   { _controller: AppBundle:Default:show }

product_update:
    path:       /product/update/{id}
    defaults:   { _controller: AppBundle:Default:update }

product_query_builder:
    path:       /product/query_builder
    defaults:   { _controller: AppBundle:Default:queryBuilder }

product_query_builder_dql:
    path:       /product/query_builder_dql
    defaults:   { _controller: AppBundle:Default:queryBuilderDql }

product_query_repository_class:
    path:       /product/query_repository_class
    defaults:   { _controller: AppBundle:Default:queryRepositoryClass }