AppBundle\Entity\Task:
    properties:
        task:
            - NotBlank: ~
            - Length:
                min: 5
                max: 100
                minMessage: "Your task name must be at least {{ limit }} characters long"
                maxMessage: "Your task name cannot be longer than {{ limit }} characters"
        dueDate:
            - NotBlank: ~
            - Type: \DateTime